complexity:
  ComplexCondition:
    excludes: ['**/test/**', '**/androidTest/**']
  LongMethod:
    threshold: 60
    excludes: ['**/test/**', '**/androidTest/**']
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
    excludes: ['**/test/**', '**/androidTest/**']
  CyclomaticComplexMethod:
    threshold: 20
    excludes: ['**/test/**', '**/androidTest/**']
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 20
    thresholdInInterfaces: 15
    excludes: ['**/test/**', '**/androidTest/**']
  NestedBlockDepth:
    threshold: 5
    excludes: ['**/test/**', '**/androidTest/**']

style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 5
  MaxLineLength:
    maxLineLength: 140
  WildcardImport:
    active: true

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Exception
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: '_|(ignore|expected).*'
